# Generated by Django 5.1.1 on 2024-09-19 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_booking_unique_together_alter_booking_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('listing', 'start_date', 'end_date'), name='unique_booking_for_dates'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
