# Generated by Django 5.1.1 on 2024-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('landlord', 'Landlord')], default='renter', max_length=10),
        ),
    ]
