# Generated by Django 5.1.1 on 2024-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('renter', 'Арендатор'), ('landlord', 'Арендодатель')], default='renter', max_length=10),
        ),
    ]
